// Generate an RGB random color that will be used to style the background color of the body

function colorBack() {
	var rgb = 256 ;
	var red = Math.floor(Math.random()*(rgb));
	var green = Math.floor(Math.random()*(rgb));
	var blue = Math.floor(Math.random()*(rgb));
	var color = 'rgb(' + red + ',' + blue + ',' + green + ')' ;
	toChangeColor(color);
	return color;
	console.log("finishing..");
	//return color;
}

// Get the body element by its ID body-color and replace its property with the generated by colorback()
function toChangeColor(color){
	var sheet = document.getElementById('bodyColor');
	sheet.style.background = color;
}
	
